### PR TITLE
fix: prevent creating a mod reference matching existing id

### LINKED ISSUE #116: Prevent creating mods with a mod reference that matches an existing mod id
https://discord.com/channels/555424930502541343/830842478956642354/1382455396047781898

### PR DESCRIPTION
**Pull request by Vilsol**
Fixes #116

### CODE REVIEW

File: tests/mod_test.go [hunk 1]
```diff
@@ -341,4 +341,53 @@ func TestMods(t *testing.T) {
 			}
 		})
 	}
+
+	t.Run("Prevent Mod Reference Matching Existing Mod ID", func(t *testing.T) {
+		// First create a mod to get its ID
+		token, _, err := makeUser(ctx)
+		testza.AssertNoError(t, err)
+
+		// Create the first mod without tags to avoid validation issues
```
Comment (budak7273) [inline tests/mod_test.go]: Tags (presumably ficsit.app tags?) don't seem to come into play with this test?
```suggestion
		// Create the first mod
```

**Review by budak7273 — CHANGES_REQUESTED** [review]

**Review by budak7273 — APPROVED** [review]
